services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
      
  callservice:
    build: ../callService
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq

  notificationservice:
    build: ../notificationService
    depends_on:
      - rabbitmq
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"